name: 'Benchmarks'

on:
  workflow_dispatch:
    inputs:
      forks:
        description: 'Number of times he JVM is forked for each benchmark'
        default: 3
      warmup-iterations:
        description: 'Number of warmup iterations for each benchmark'
        default: 15
      iterations:
        description: 'Number of iterations for each benchmark'
        default: 15
      benchmark-regex:
        description: 'Regex specifying which benchmarks to run'
        default: '.*'

jobs:
  benchmark:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout Repository'
      uses: 'actions/checkout@v2'
    - name: 'Setup Java'
      uses: 'actions/setup-java@v1'
      with:
        java-version: 11
    - name: 'Perform Benchmarks'
      run: >
        sbt 'benchmarks/jmh:run
        -f ${{ github.event.inputs.forks }}
        -wi ${{ github.event.inputs.warmup-iterations }}
        -i ${{ github.event.inputs.iterations }}
        -rf csv
        -rff results/benchmark-${{ github.run_number }}.csv
        ${{ github.event.inputs.benchmark-regex }}'
    - name: 'Commit Benchmark Results'
      uses: EndBug/add-and-commit@v6
      with:
        add: 'benchmarks/results/benchmark-${{ github.run_number }}.csv'
        message: 'Add benchmark results for benchmark run ${{ github.run_number }}'
