name: 'Benchmark'

on:
  workflow_dispatch:
    inputs:
      forks:
        description: 'Number of times the JVM is forked for each benchmark'
        default: 1
      warmup-iterations:
        description: 'Number of warmup iterations for each benchmark'
        default: 15
      iterations:
        description: 'Number of iterations for each benchmark'
        default: 15
      benchmark-regex:
        description: 'Regex specifying which benchmarks to run'
        default: '.*'

jobs:
  benchmark:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout Repository'
      uses: 'actions/checkout@v2'
    - name: 'Setup Java'
      uses: 'actions/setup-java@v1'
      with:
        java-version: 11
    - name: 'Cache SBT And Dependencies'
      uses: 'actions/cache@v2'
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: 'os-${{ runner.os }}-sbt-${{ hashFiles(''build.sbt'', ''project/build.properties'', ''project/plugins.sbt'') }}'
        restore-keys: 'os-${{ runner.os }}-sbt-'
    - name: 'Benchmark Project'
      run: >
        sbt 'benchmarks/jmh:run
        -f ${{ github.event.inputs.forks }}
        -wi ${{ github.event.inputs.warmup-iterations }}
        -i ${{ github.event.inputs.iterations }}
        -rf csv
        -rff results/benchmark-${{ github.run_number }}.csv
        ${{ github.event.inputs.benchmark-regex }}'
    - name: 'Create Pull Request'
      uses: 'peter-evans/create-pull-request@v3'
      with:
        title: 'Feature: Benchmark ${{ github.run_number }} Results'
        branch: 'feature/benchmark-${{ github.run_number }}-results'
        commit-message: 'Add benchmark results for benchmark run ${{ github.run_number }}'
        delete-branch: true
